name: TROJail-test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.58.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - astor==0.8.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - blake3==1.0.8
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - codetiming==1.4.0
      - colorful==0.5.8
      - compressed-tensors==0.9.2
      - contourpy==1.3.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==4.0.0
      - debugpy==1.8.15
      - decorator==5.2.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - einops==0.8.1
      - email-validator==2.3.0
      - eval-type-backport==0.2.2
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fast-bleu==0.0.90
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.11.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.20.3
      - flash-attn==2.7.4.post1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gym-sokoban==0.0.6
      - gymnasium==1.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - interegular==0.3.3
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.12
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistral-common==1.8.8
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.126
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.6.1
      - omegaconf==2.3.0
      - openai==2.15.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.5
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==26.0
      - pandas==2.3.1
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post7
      - peft==0.16.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==23.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pybind11==3.0.0
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.0
      - pydantic-settings==2.12.0
      - pygame==2.6.1
      - pygments==2.19.2
      - pylatexenc==2.10
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.50.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.6.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - together==1.5.21
      - tokenizers==0.21.4
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.53.2
      - triton==3.2.0
      - typer==0.15.4
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - verl==0.2.0.dev0
      - virtualenv==20.36.1
      - vllm==0.8.2
      - wandb==0.21.0
      - watchfiles==1.1.1
      - wcwidth==0.3.2
      - websockets==16.0
      - werkzeug==3.1.5
      - wrapt==2.0.1
      - xformers==0.0.29.post2
      - xgrammar==0.1.16
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
